---
# Source: env-deployments/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: react-ui
    env: dev
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: react-ui
  type: NodePort
---
# Source: env-deployments/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-dep
  labels:
    app: react-ui
    env: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
        env: dev
    spec:
      containers:
        - name: react-ui
          image: vikashashoke/ui
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.2
              memory: 500Mi
            requests:
              cpu: 0.2
              memory: 500Mi
---
# Source: env-deployments/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    app: react-ui
    env: dev
spec:
  maxReplicas: 10
  minReplicas: 4
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: react-ui
  targetCPUUtilizationPercentage: 50
